name: Publish Docker images
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'
env:
  DOCKER_IMAGE_PREFIX: almalinux-perlbrew
jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        branch: ['8', '9', 'latest']
        folder: ['base', 'pyenv3', 'pyenv3-java']
    steps:
      -
        name: Checkout
        uses: Bhacaz/checkout-files@v2
        with:
          files: ${{matrix.folder}}
          branch: ${{ matrix.branch }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Sets env vars for Docker image
        run: |
          echo "DOCKER_IMAGE_BRANCH=latest" >> $GITHUB_ENV
        if: ${{ matrix.branch == 'main' }}
      - name: Sets env vars for Docker image
        run: |
          echo "DOCKER_IMAGE_BRANCH=${{ matrix.branch }}" >> $GITHUB_ENV
        if: ${{ matrix.branch != 'main' }}
      - name: Push Docker
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_ACCOUNT }}/${{env.DOCKER_IMAGE_PREFIX}}-${{ matrix.folder }}:${{ env.DOCKER_IMAGE_BRANCH }}
            ghcr.io/${{ github.repository_owner }}/docker-{{env.DOCKER_IMAGE_PREFIX}}-${{ matrix.folder }}:${{ env.DOCKER_IMAGE_BRANCH }}
